### ISSUE TITLE
Mvn error

### ISSUE THREAD

**Issue by KikyoC** [IamTheDefender/BW1058-Cosmetics#33]
Hello, I'm trying to edit the plugin, but I don't know how to compile this plugin.

When I run any mvn command, I still have this error: [ERROR] Failed to execute goal on project BW1058-Cosmetics: Could not resolve dependencies for project me.defender:BW1058-Cosmetics:jar:1.4.5: The following artifacts could not be resolved: com.andrei1058.bedwars:BedWars1058:jar:23.3, com.andrei1058.bedwars:BedWarsProxy:jar:1.2.4: Could not find artifact com.andrei1058.bedwars:BedWars1058:jar:23.3 at specified path C:\Users\togau\IdeaProjects\BW1058-Cosmetics\lib\bedwars-plugin-23.3.jar -> [Help 1]

Can anyone help me please ?
Thank you in advance

**Comment by IamTheDefender** [comment]
Not an issue of the plugin, do not open this kind of issues, you will not receive coding help here, please use Google or chatGPT instead
